### PR TITLE
feat(pubsub): support message filtering in pstest

### PR DESCRIPTION
**Pull request by zezhehh**
Resolves https://github.com/googleapis/google-cloud-go/issues/8582

The implementation:
- Parse the filter string using `go.einride.tech/aip`.
- Match each message attributes with the filter and remove the message if the match fails.

### CODE REVIEW

**Comment by andreas-lindfalk** [comment]
@shollyman review por favor...

**Comment by vlasn** [comment]
@shollyman Friendly nudge, would love to leverage this.

**Comment by hongalex** [comment]
Thank you so much for the PR. Apologies as I somehow didn't see this for the longest time. For the most part the PR looks good but I need to confirm with the team on how to tackle this since we generally try to minimize the number of third party libraries.

**Comment by zezhehh** [comment]
@hongalex Hi! Thanks for your reviews. Just added test for escapes characters and rebased to main.

**Review by hongalex — APPROVED** [review]

**Comment by hongalex** [comment]
Checks are failing because of a minor formatting issue that running `go vet` should solve.

**Comment by zezhehh** [comment]
> Checks are failing because of a minor formatting issue that running `go vet` should solve.

Thanks! Seems it requires another approval :)

**Comment by hongalex** [comment]
One more vet issue, the exported `ValidateFilter` method needs a comment there.

**Comment by zezhehh** [comment]
> One more vet issue, the exported `ValidateFilter` method needs a comment there.

Added the comment. Couldn't succeed in running `vet.sh` locally. Hopefully, it works this time.

**Comment by zezhehh** [comment]
Checked the error message stating that `TestUpdateFilter` failed due to a bad filter string. Already updated! 🙌

(However, the test `TestSubscriptionMessageOrdering` still fails on my computer in both the main and this branch. It seems unrelated to this PR.)

**Comment by aalobai1** [comment]
I'm so happy this is merged, thank you gcloud team ❤️

**Pull request merged**
