### PR TITLE
chore(all): update dependencies

### PR DESCRIPTION
**Pull request by ma-g-22**
Files generated using below command: 
`go get google.golang.org/api@latest && go work sync`

Similar PR in the past: https://github.com/googleapis/google-cloud-go/pull/9794

New genproto version is required in Bigtable to incorporate [automated backups ](https://github.com/googleapis/google-cloud-go/pull/9702#discussion_r1591538269)

### CODE REVIEW

**Comment by noahdietz** [comment]
If there is a specific dep you need updated, please open an issue or contact the team internally.

**Comment by noahdietz** [comment]
Sorry shouldn't have closed, pressed "close with comment" instead of "comment"

**Comment by bhshkh** [comment]
@noahdietz , this is required for adding automated backups (https://github.com/googleapis/google-cloud-go/pull/9702)
The [latest PR](https://github.com/googleapis/google-cloud-go/pull/10116) generated by renovate bot did not update the genproto 
CC: @quartzmo

**Comment by noahdietz** [comment]
> @noahdietz , this is required for adding automated backups (#9702) The [latest PR](https://github.com/googleapis/google-cloud-go/pull/10116) generated by renovate bot did not update the genproto CC: @quartzmo

Updating one module that needs the change is fine. Do all of them need to be updated though? It's just the kind of thing we prefer to let the bot do unless there is a bug/vulnerability we need to manually patch.

**Comment by ma-g-22** [comment]
Thanks. OK, adding the dependency updates to the feature change PR

**Pull request closed without merging**
