### PR TITLE
chore(firestore): Clarify Transaction.Get error code

### LINKED ISSUE #6174: firestore: `Transaction.Get()` is missing document about error code
`Transaction.Get()` does not have any document about its error code, while `DocumentRef.Get()` comment states that it returns a `NotFound` error when the document does not exist.

https://github.com/googleapis/google-cloud-go/blob/06721e06a16f5c94a31b96809aad02f5eb38147c/firestore/docref.go#L66-L71

### PR DESCRIPTION
**Pull request by ordovicia**
Clarifies that `Transaction.Get()` returns an error with `NotFound` status code.

`DocumentRef.Get()` comment already states that it returns `NotFound` error.

https://github.com/googleapis/google-cloud-go/blob/06721e06a16f5c94a31b96809aad02f5eb38147c/firestore/docref.go#L66-L71

Fixes #6174

### CODE REVIEW

**Comment by ordovicia** [comment]
@enocom @telpirion Please take a look. Thank you.

**Comment by telpirion** [comment]
@ordovicia Please create a GitHub issue to track your request, per CONTRIBUTING guidelines. Thanks!

**Comment by ordovicia** [comment]
Ah, sorry. I created an issue #6174.

**Comment by ordovicia** [comment]
@telpirion @enocom Hi, please take a look again. Thank you.

**Comment by ordovicia** [comment]
@telpirion @enocom Ping?

**Comment by ordovicia** [comment]
@telpirion @enocom Ping?

**Comment by ordovicia** [comment]
@telpirion @enocom Ping?

**Review by enocom — APPROVED** [review]

**Comment by enocom** [comment]
@ordovicia Sorry for the slow response. This got lost in all my other GitHub emails. Thanks for the docs update!

**Pull request merged**
