### PR TITLE
chore: carve out sub-modules

### PR DESCRIPTION
**Pull request by codyoss**
This commit will be tagged:
- v0.92.3
- cloudbuild/v0.1.0
- monitoring/v0.1.0
- secretmanager/v0.1.0
- video/v0.1.0
- security/v0.1.0
- gkehub/v0.1.0
- gkeconnect/v0.1.0
- area120/v0.1.0
- analytics/v0.1.0

### CODE REVIEW

**Comment by codyoss** [comment]
Command to be run post merge: 

```
git tag v0.92.3 $COMMIT_SHA
git tag cloudbuild/v0.1.0 $COMMIT_SHA
git tag monitoring/v0.1.0 $COMMIT_SHA
git tag secretmanager/v0.1.0 $COMMIT_SHA
git tag video/v0.1.0 $COMMIT_SHA
git tag security/v0.1.0 $COMMIT_SHA
git tag gkehub/v0.1.0 $COMMIT_SHA
git tag gkeconnect/v0.1.0 $COMMIT_SHA
git tag area120/v0.1.0 $COMMIT_SHA
git tag analytics/v0.1.0 $COMMIT_SHA

git push origin refs/tags/v0.92.3
git push origin refs/tags/cloudbuild/v0.1.0
git push origin refs/tags/monitoring/v0.1.0
git push origin refs/tags/secretmanager/v0.1.0
git push origin refs/tags/video/v0.1.0
git push origin refs/tags/security/v0.1.0
git push origin refs/tags/gkehub/v0.1.0
git push origin refs/tags/gkeconnect/v0.1.0
git push origin refs/tags/area120/v0.1.0
git push origin refs/tags/analytics/v0.1.0
```

**Comment by codyoss** [comment]
I am still exploring getting iam and compute split in this PR. But there is currently code in the root module that depends on these libraries which is causing some issues.

**Comment by codyoss** [comment]
Going to move forward with these. I think there is a way to still carve out iam and compute but I need to do a little more testing to ensure. After this batch is released though I will reopen the regen pipeline. I don't want to block updates while I am testing things out.

**Review by tbpg — APPROVED** [review]

**Comment by codyoss** [comment]
Failure is expected due to tag not yet existing. Merging.

**Pull request merged**
