### PR TITLE
storage: fix scheme lost when use endpoint

### PR DESCRIPTION
**Pull request by 3pointer**
Client should choose the correct scheme when using the endpoint with scheme (http://localhost:8080). or it will return 
`Get https://localhost:8080/xxx: http: server gave HTTP response to HTTPS client"` when client try to use [NewRangeReader](https://github.com/googleapis/google-cloud-go/blob/c66c5b8799db244755c353f47d159830c8ee4e7c/storage/reader.go#L110) to read objects.

### CODE REVIEW

**Comment by 3pointer** [comment]
@googlebot I signed it!

**Comment by 3pointer** [comment]
Hi, Is there any chance for this PR merged?

**Comment by 3pointer** [comment]
Test Case Failed in https://github.com/googleapis/google-cloud-go/blob/master/storage/storage_test.go#L1285-L1287.

`WantRawBasePath` is `https://xxx` but `WantScheme` is `http`, is this test case wrong? or did I miss something?

**Comment by 3pointer** [comment]
> Test Case Failed in https://github.com/googleapis/google-cloud-go/blob/master/storage/storage_test.go#L1285-L1287.
> 
> `WantRawBasePath` is `https://xxx` but `WantScheme` is `http`, is this test case wrong? or did I miss something?

@ddelgrosso1 could you help me with this?

**Comment by BrennaEpp** [comment]
Hi @3pointer, thank you for filing this PR and raising this issue. We are currently looking at related issues and investigating why this is failing. I will update once we know more.

**Comment by BrennaEpp** [comment]
Hi @3pointer, I created a PR against your branch to fix the failing test. If you agree with those changes, please merge and then we can merge this in.

**Comment by BrennaEpp** [comment]
Similar changes were merged in. Thanks for your contribution! Please open an issue or reopen this request if you are still having issues.

**Pull request closed without merging**
