### PR TITLE
vertexai: fix typo in README

### PR DESCRIPTION
**Pull request by bytemare**

### CODE REVIEW

**Comment by Carebear11809** [comment]
What is this

**Review by eliben — APPROVED** [review]

**Comment by eliben** [comment]
Thank you! Please sign the CLA per the bot's comment and then we can merge this

**Comment by bytemare** [comment]
Hi @eliben, done ! Thank you for your patience

**Comment by eliben** [comment]
@bytemare not sure what happened here, I asked the GitHub UI to rebase this PR on the main branch. I cannot see the original PR - can you re-create a new one?

**Pull request closed without merging**
