### PR TITLE
feat(firestore): add support for FirebaseEvent

### PR DESCRIPTION
**Pull request by jsmouret**
Add useful tooling to work with Firebase triggers.
See #1438

### CODE REVIEW

**Comment by codyoss** [comment]
I wonder if https://github.com/googleapis/google-cloudevents-go is the correct place for this, these events might already exist there.

**Comment by jsmouret** [comment]
It seems to match those [structures](https://github.com/googleapis/google-cloudevents-go/blob/master/cloud/firestore/v1/document_event_data.go) but I don't see any logic in the repo. It is only definitions.

**Comment by jsmouret** [comment]
... and they look different from the original [documentation](https://cloud.google.com/functions/docs/calling/cloud-firestore#code_sample)

**Comment by codyoss** [comment]
@jsmouret  Correct, that repo in just meant to have code for the different event types. Would you mind opening up an issue for the "glue code" and describe why you think adding it would be beneficial.

**Comment by jsmouret** [comment]
Can I piggyback on that issue #1438 ? or do you prefer a new one?

**Comment by codyoss** [comment]
@googleapis/api-firestore Can we decide what to do with this PR?

**Comment by jsmouret** [comment]
Not using firebase anymore, so closing this PR

**Pull request closed without merging**
