### PR TITLE
feat(spanner): support NUMERIC in mutations

### PR DESCRIPTION
**Pull request by apstndb**
This PR adds support of NUMERIC type in mutations.
ref #3327

### CODE REVIEW

**Review by olavloite — APPROVED** [review]
Good catch, thanks for fixing this.

It would have been good to have a test case that would note this in case there are new data types added in the future, but apparently that is missing. We can add that through a separate PR.

**Comment by olavloite** [comment]
@tbpg Do you have any idea why the kokoro run seems to be hanging indefinitely? I've tried to trigger the execution a number of times, but it never seems to finish (or report a status).

**Comment by tbpg** [comment]
@olavloite, sorry, just saw this. I added the label to start Kokoro. Must have missed the initial webhook or something.

**Comment by olavloite** [comment]
> @olavloite, sorry, just saw this. I added the label to start Kokoro. Must have missed the initial webhook or something.

No problem, thanks for looking into it :-)

**Pull request merged**
