### PR TITLE
feat(internal/detect): add helper to detect projectID from env

### PR DESCRIPTION
**Pull request by codyoss**
This is meant to be used by certain veneers so that we can detect the projectID in a consistent manner. Future PRs will use this logic.
Fixes: #1294

### CODE REVIEW

**Comment by codyoss** [comment]
cc @crwilcox Some of your libraries can use this in the future. I think you brought this up not too long ago...

**Review by noahdietz — APPROVED** [review]
LGTM but is there a way to add a test?

**Comment by crwilcox** [comment]
How does this differ from https://github.com/googleapis/google-cloud-go/blob/master/firestore/client.go#L83 / https://github.com/googleapis/google-cloud-go/blob/master/firestore/client.go#L104

Is the goal here to centralize this as most veneers have this (more or less) duplicated code?

**Comment by codyoss** [comment]
@crwilcox 

> Is the goal here to centralize this as most veneers have this (more or less) duplicated code?

Yes. Just wanted to have a consistent implementation for all to use.

**Comment by codyoss** [comment]
@noahdietz Done.

**Pull request merged**
