### PR TITLE
chore(internal/actions): refactor changefinder

### PR DESCRIPTION
**Pull request by noahdietz**
Refactors `changefinder` to support nested submodules i.e. `vision/v2`.

Changes the default compare the current `HEAD` against `origin/main`.

Add a `-q` quiet mode, all logs will be buffered and dumped in the event of an error.

Add a `-dir` flag to specify a different root dir than the default of `cwd`.

Add a `-format` flag with values `plain` (stdout, new line delimited), and `github` (prints github action output). Defaults to `plain`.

Add a `-gh-var` flag that accepts the name of the GitHub variable the output should set,  defaults to `submodules`.

This will be able to replace the git-fu used in the `apidiff` workflow and it can power a "change description" action, basically the inverse of the `apidiff` workflow that reports the _added_ surfaces.

Try it out by running the following:
```
cd $GOOGLE_CLOUD_GO
git checkout origin owl-bot-copy
go run ./internal/actions/cmd/changefinder -q
```

### CODE REVIEW

**Comment by quartzmo** [comment]
I wasn't aware of changefinder before this PR. It doesn't appear to have any documentation whatsoever. What do you think about adding a short README or even just a few sentences of function docs for `main`? The description for this PR has some useful content.

**Comment by noahdietz** [comment]
> I wasn't aware of changefinder before this PR. It doesn't appear to have any documentation whatsoever. What do you think about adding a short README or even just a few sentences of function docs for `main`? The description for this PR has some useful content.

Great idea.

Honestly, I wasn't aware of it either until I started to consider writing the exact same thing and bumped into it while starting to do so :)

**Comment by quartzmo** [comment]
I think this module and file are currently orphaned. It was added in #4537 and referenced only in `.github/workflows/release-submodule.yaml`, which no longer exists.

**Comment by noahdietz** [comment]
> I think this module and file are currently orphaned. It was added in #4537 and referenced only in `.github/workflows/release-submodule.yaml`, which no longer exists.

Well I'm glad it wasn't removed, because it's quite useful!

**Comment by quartzmo** [comment]
Can you add your new usage(s) to this PR?

**Comment by noahdietz** [comment]
> Can you add your new usage(s) to this PR?

If it is OK, I'd prefer to make that change in a separate PR in case I need to revert it (i.e. i break the `apidiff` workflow).

**Review by quartzmo — APPROVED** [review]

**Comment by noahdietz** [comment]
Add a README!

**Pull request merged**
