### PR TITLE
chore(spanner): drop errors backwards compatibility

### LINKED ISSUE #10322: spanner: unnecessary workaround for errors
Issue for https://github.com/googleapis/google-cloud-go/pull/9757

Currently it's still using workarounds for Go1.12, which are no longer supported https://github.com/googleapis/google-cloud-go/blob/main/spanner/errors112.go -- that code can be removed.

### PR DESCRIPTION
**Pull request by egonelbre**
The repo states that the supported Go versions are 1.19+.

Fixes #10322

### CODE REVIEW

**Comment by codyoss** [comment]
@rahul2393 for review

**Comment by rahul2393** [comment]
Hello @egonelbre can you please help fix the conflicts

**Comment by egonelbre** [comment]
@rahul2393 done. In this case the conflict was in go.mod where some dependencies got removed. To get things in sync, I got the main branch state of `go.mod` and `go.sum` and then ran `go mod tidy` -- this re-removed the dependency and got things in sync.

**Comment by egonelbre** [comment]
@rahul2393 this ended up going in conflict again. It is frustrating trying to keep this up to date.

**Review by rahul2393 — APPROVED** [review]

**Pull request merged**
