### PR TITLE
docs(datastore): say to call (*Client).Close

### PR DESCRIPTION
**Pull request by tbpg**

### CODE REVIEW

**Review by codyoss — APPROVED** [review]
LGTM, do you think this is something we should be doing holistically across all clients? Even in the generated layers?

**Comment by codyoss** [comment]
Or maybe this would be nice to put in a sort of best practices doc we put in some readme.

**Comment by tbpg** [comment]
> do you think this is something we should be doing holistically across all clients?

Yes. This has caused issues for new and experienced users. So, additional nudges seem necessary.

Maybe GoDoc and a best practices doc?

**Comment by tbpg** [comment]
Filed https://github.com/googleapis/google-cloud-go/issues/3031.

**Pull request merged**
