### PR TITLE
feat(storage): add BucketName to BucketHandle

### PR DESCRIPTION
**Pull request by derekperkins**
The bucket name is currently only accessible via the Attrs() network call, and can be trivially returned from the bucket handle. Today we have to pass around a `BucketHandle` and the bucket name separately.

I used BucketName instead of just Name, as ObjectHandle has both BucketName and ObjectName.

### CODE REVIEW

**Review by tritone — COMMENTED** [review]
This looks fine to me. The `go vet` check is failing on `go fmt`, could you fix that?

**Comment by derekperkins** [comment]
I used the web editor and left a stray tab. That should be resolved now.

**Review by tritone — APPROVED** [review]

**Comment by derekperkins** [comment]
@tritone any blockers before merging this?

**Comment by derekperkins** [comment]
Thanks!

**Pull request merged**
