### PR TITLE
docs(pubsublite): add readme for pubsublite

### PR DESCRIPTION
**Pull request by anguillanneuf**
Set expectation for users.

### CODE REVIEW

**Review by hongalex — APPROVED** [review]

**Review by hongalex — COMMENTED** [review]
Can you add the license header here too?
Edit: actuslly license header is only needed for doc.go. could you add that file as well? Thanks!

**Comment by anguillanneuf** [comment]
@hongalex What goes in doc.go for Pub/Sub Lite? Could that be in a separate PR?

**Comment by hongalex** [comment]
Yeah, just the same warning message. We can flesh out the details later.

**Comment by anguillanneuf** [comment]
Sounds good. Done.

**Pull request merged**
