### PR TITLE
spanner: remove appengine-specific numChannels.

### PR DESCRIPTION
**Pull request by hengfengli**
Fixes: #1553

### CODE REVIEW

**Comment by hengfengli** [comment]
> The change itself looks good to me. What is the exact reason that we can drop this now?

From the issue description, it seems that we somehow must do this for Go 1.9 because App Engine used to support that. Now, the standard env only supports 1.12+ and 1.11 so that we don't have to do this. But from what I can see, the flexible env still supports 1.9 (https://cloud.google.com/appengine/docs/go).

**Comment by hengfengli** [comment]
In https://github.com/googleapis/google-cloud-go#go-versions-supported, we say: 

> We support the two most recent major versions of Go. If Google App Engine uses an older version, we support that as well.

Now, I am a bit confused. In the flexible env of Google App Engine, it still supports 1.9 as its oldest version. @skuruppu Do you think we should merge this? This issue has been in the queue for almost 1 year.

**Comment by hengfengli** [comment]
@broady Do you have any thought about this? Are we safe to remove them?

**Comment by hengfengli** [comment]
@broady Just a follow-up with this PR. Do you have any thoughts?

**Comment by broady** [comment]
Sorry, didn't see this. LGTM.

**Comment by Capstan** [comment]
In terms of safety, https://cloud.google.com/appengine/docs/deprecations/ states Go 1.9 was shut down June 30, 2020, so there's not a concern there.

Also 🎉 !

**Pull request merged**
