### PR TITLE
storage: bucket exists func implemented

### PR DESCRIPTION
**Pull request by eftalyurtseven**
I didn't find any method for checking bucket exists or not,
This PR simply checks the whether bucket exists or not. 
Stackoverflow: https://stackoverflow.com/a/52935830/5905905

### CODE REVIEW

**Comment by tritone** [comment]
Hi @eftalyurtseven , thanks very much for contributing.

I am inclined not to merge this because it's just a wrapper for the existing `BucketHandle.Attrs` method. In general we try to keep the exported surface for this library as small as possible, unless we have a strong need to expand it.

However, I'll leave the PR open for now in case others have thoughts. (I know some of the other language GCS clients have a similar bucket.Exists method).

**Review by tritone — COMMENTED** [review]
Hi @eftalyurtseven , thanks very much for contributing.

I am inclined not to merge this because it's just a wrapper for the existing `BucketHandle.Attrs` method. In general we try to keep the exported surface for this library as small as possible, unless we have a strong need to expand it.

However, I'll leave the PR open for now in case others have thoughts. (I know some of the other language GCS clients have a similar bucket.Exists method).

**Comment by eftalyurtseven** [comment]
Hi @tritone,thank you very much for your quick and friendly response.

I saw different pattern in python client. If I migrate to golang this func with .Query, will it be possible solution for this?

**Comment by codyoss** [comment]
Closing based on @tritone comment above.

**Pull request closed without merging**
