### PR TITLE
chore(all): update all deps

### PR DESCRIPTION
**Pull request by broady**
For each module:

```
go get -d $(go list -m -f '{{if not .Indirect}}{{.Path}}{{end}}' all)
go mod tidy
```

### CODE REVIEW

**Comment by broady** [comment]
Oops, yep, commit message wasn't accurate :|

**Comment by broady** [comment]
I can't replicate the mod tidy failure.

https://source.cloud.google.com/results/invocations/3f263f05-5f4e-4db6-8671-6efc7cd733e3/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Fgo113/log

```
+ git diff go.sum
+ read
diff --git a/go.sum b/go.sum
index e43397a0..a8069f7a 100644
--- a/go.sum
+++ b/go.sum
@@ -472,6 +472,7 @@ honnef.co/go/tools v0.0.1-2019.2.3 h1:3JgtbtFHMiCmsznwGVTUWbgGov+pVqnlf1dEJTNAXe
 honnef.co/go/tools v0.0.1-2019.2.3/go.mod h1:a3bituU0lyd329TUQxRnasdCoJDkEUEAqEt0JzvZhAg=
 honnef.co/go/tools v0.0.1-2020.1.3 h1:sXmLre5bzIR6ypkjXCDI3jHPssRhc8KD/Ome589sc3U=
 honnef.co/go/tools v0.0.1-2020.1.3/go.mod h1:X/FiERA/W4tHapMX5mGpAtMSVEeEUOyHaw9vFzvIQ3k=
+honnef.co/go/tools v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
 honnef.co/go/tools v0.0.1-2020.1.4/go.mod h1:X/FiERA/W4tHapMX5mGpAtMSVEeEUOyHaw9vFzvIQ3k=
 rsc.io/binaryregexp v0.2.0 h1:HfqmD5MEmC0zvwBuF187nq9mdnXjXsSivRiXN7SmRkE=
 rsc.io/binaryregexp v0.2.0/go.mod h1:qTv7/COck+e2FymRvadv62gMdZztPaShugOCi3I+8D8=
cleanup
```

Locally:

```
cbro@birdup:~/modsrc/gocloud$ go1.13.12 version
go version go1.13.12 linux/amd64
cbro@birdup:~/modsrc/gocloud$ go1.13.12 clean --modcache
cbro@birdup:~/modsrc/gocloud$ go1.13.12 mod download
go: finding cloud.google.com/go/bigquery v1.8.0
go: finding cloud.google.com/go/datastore v1.1.0
go: finding cloud.google.com/go/pubsub v1.3.1
go: finding cloud.google.com/go/storage v1.10.0
go: finding dmitri.shuralyov.com/gpu/mtl v0.0.0-20190408044501-666a987793e9
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/BurntSushi/xgb v0.0.0-20160522181843-27f122750802
go: finding github.com/census-instrumentation/opencensus-proto v0.2.1
go: finding github.com/chzyer/logex v1.1.10
go: finding github.com/chzyer/readline v0.0.0-20180603132655-2972be24d48e
go: finding github.com/chzyer/test v0.0.0-20180213035817-a1ea475d72b1
go: finding github.com/client9/misspell v0.3.4
go: finding github.com/cncf/udpa/go v0.0.0-20191209042840-269d4d468f6f
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/envoyproxy/go-control-plane v0.9.4
go: finding github.com/envoyproxy/protoc-gen-validate v0.1.0
go: finding github.com/go-gl/glfw v0.0.0-20190409004039-e6da0acd62b1
go: finding github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200222043503-6f7a984d4dc4
go: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: finding github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: finding github.com/golang/mock v1.4.3
go: finding github.com/golang/protobuf v1.4.2
go: finding github.com/google/btree v1.0.0
go: finding github.com/google/go-cmp v0.5.0
go: finding github.com/google/martian v2.1.0+incompatible
go: finding github.com/google/pprof v0.0.0-20200708004538-1a94d8640e99
go: finding github.com/google/renameio v0.1.0
go: finding github.com/googleapis/gax-go/v2 v2.0.5
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/ianlancetaylor/demangle v0.0.0-20181102032728-5e5cf60278f6
go: finding github.com/jstemmer/go-junit-report v0.9.1
go: finding github.com/kisielk/gotool v1.0.0
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/kr/pty v1.1.1
go: finding github.com/kr/text v0.1.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: finding github.com/rogpeppe/go-internal v1.3.0
go: finding github.com/stretchr/objx v0.1.0
go: finding github.com/stretchr/testify v1.4.0
go: finding github.com/yuin/goldmark v1.1.32
go: finding go.opencensus.io v0.22.4
go: finding golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: finding golang.org/x/exp v0.0.0-20200224162631-6cc2880d07d6
go: finding golang.org/x/image v0.0.0-20190802002840-cff245a6509b
go: finding golang.org/x/lint v0.0.0-20200302205851-738671d3881b
go: finding golang.org/x/mobile v0.0.0-20190719004257-d2bd2a29d028
go: finding golang.org/x/mod v0.3.0
go: finding golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: finding golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
go: finding golang.org/x/sync v0.0.0-20200625203802-6e8e738ad208
go: finding golang.org/x/sys v0.0.0-20200523222454-059865788121
go: finding golang.org/x/text v0.3.3
go: finding golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: finding golang.org/x/tools v0.0.0-20200708183856-df98bc6d456c
go: finding golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: finding google.golang.org/api v0.29.0
go: finding google.golang.org/appengine v1.6.6
go: finding google.golang.org/genproto v0.0.0-20200709005830-7a2ca40e9dc3
go: finding google.golang.org/grpc v1.30.0
go: finding google.golang.org/protobuf v1.25.0
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding gopkg.in/errgo.v2 v2.1.0
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding honnef.co/go/tools v0.0.1-2020.1.4
go: finding rsc.io/binaryregexp v0.2.0
go: finding rsc.io/quote/v3 v3.1.0
go: finding rsc.io/sampler v1.3.0
cbro@birdup:~/modsrc/gocloud$ go1.13.12 mod tidy
cbro@birdup:~/modsrc/gocloud$ git diff
cbro@birdup:~/modsrc/gocloud$
```

**Comment by codyoss** [comment]
Did a little digging, this is the offending line:

https://github.com/googleapis/google-cloud-go/blob/4333cce1096f0681fc2ba2939c17eeb6724951ef/internal/kokoro/vet.sh#L34

Installing here is no longer necessary as it is baked into the image. Ill make a PR to remove this

**Comment by codyoss** [comment]
Merged so I can get this out in the release I am prepping.

**Pull request merged**
