### PR TITLE
fix(bigtable/bttest): Cells per row offset filters didn't implement truthiness correctly, breaking conditional filters

### PR DESCRIPTION
**Pull request by jimfulton**
Fixes: #1712

### CODE REVIEW

**Comment by jimfulton** [comment]
The samples failure seems to be unrelated to this change.

```
# contrib.go.opencensus.io/exporter/stackdriver
/go/pkg/mod/contrib.go.opencensus.io/exporter/stackdriver@v0.13.8/stats.go:459:19: end.Sub(start).Milliseconds undefined (type time.Duration has no field or method Milliseconds)
```

Another completely unrelated PR, #4286  has the same error.

The text `end.Sub(start).Milliseconds` doesn't appear in this repository.

**Review by crwilcox — APPROVED** [review]

**Comment by jimfulton** [comment]
FTR, I can't merge this. :)

**Comment by garye** [comment]
I also tried to merge this but must have lost permission to do so sometime in the last 5 years :) Seems ready to go, though.

**Comment by jimfulton** [comment]
@crwilcox I'm not allowed to merge. Can you merge this?

**Pull request merged**
