### PR TITLE
chore(internal/gapicgen): update microgen to v0.20.0

### PR DESCRIPTION
**Pull request by noahdietz**
Introduces a number of documentation/comment fixes as well a refactor of the generated code that moves the transport specific (i.e. gRPC) client implementation behind a generated interface used within a generic client. This results in a few breakages to manual code that reference internal attributes. The following diff represents the changes that should be made to fix the build:

```
diff --git a/secretmanager/apiv1/iam.go b/secretmanager/apiv1/iam.go
index e3d78a54c..948ffe3cd 100644
--- a/secretmanager/apiv1/iam.go
+++ b/secretmanager/apiv1/iam.go
@@ -22,5 +22,10 @@ import (
 // indicated by the given resource path. Name should be of the format
 // `projects/my-project/secrets/my-secret`.
 func (c *Client) IAM(name string) *iam.Handle {
-	return iam.InternalNewHandleGRPCClient(c.client, name)
+	// Until a REST transport is generated, it will always be a gRPC client
+	// under the hood.
+	if gc, ok := c.internalClient.(*gRPCClient); ok {
+		return iam.InternalNewHandleGRPCClient(gc.client, name)
+	}
+	return iam.InternalNewHandle(nil, name)
 }
diff --git a/secretmanager/apiv1beta1/iam.go b/secretmanager/apiv1beta1/iam.go
index 9d5fd4bf7..e6281f53b 100644
--- a/secretmanager/apiv1beta1/iam.go
+++ b/secretmanager/apiv1beta1/iam.go
@@ -22,5 +22,10 @@ import (
 // indicated by the given resource path. Name should be of the format
 // `projects/my-project/secrets/my-secret`.
 func (c *Client) IAM(name string) *iam.Handle {
-	return iam.InternalNewHandleGRPCClient(c.client, name)
+	// Until a REST transport is generated, it will always be a gRPC client
+	// under the hood.
+	if gc, ok := c.internalClient.(*gRPCClient); ok {
+		return iam.InternalNewHandleGRPCClient(gc.client, name)
+	}
+	return iam.InternalNewHandle(nil, name)
 }
diff --git a/spanner/apiv1/spanner_client_options.go b/spanner/apiv1/spanner_client_options.go
index 639e890d4..5b924b5d1 100644
--- a/spanner/apiv1/spanner_client_options.go
+++ b/spanner/apiv1/spanner_client_options.go
@@ -21,5 +21,5 @@ import "google.golang.org/api/option"
 // This function is only intended for use by the client library, and may be
 // removed at any time without any warning.
 func DefaultClientOptions() []option.ClientOption {
-	return defaultClientOptions()
+	return defaultGRPCClientOptions()
 }

```

Also update `protoc-gen-go` to `v1.5.2` in the Docker image.

### CODE REVIEW

**Comment by codyoss** [comment]
Looks like the Dockfile does not build as is:

```
#13 21.61 go get: github.com/googleapis/gapic-generator-go@v0.20.0 (matching github.com/googleapis/gapic-generator-go/cmd/protoc-gen-go_gapic@v0.20.0) requires github.com/golang/protobuf@v1.5.2, not github.com/golang/protobuf@v1.4.3 (matching github.com/golang/protobuf/protoc-gen-go@v1.4.3)
```

**Comment by noahdietz** [comment]
@codyoss is there any reason to not update the protobuf Go version installed?

**Comment by codyoss** [comment]
Nope, I think that is fine!

**Comment by noahdietz** [comment]
Done! Build seemed to work locally.

**Review by codyoss — APPROVED** [review]

**Pull request merged**
