### PR TITLE
chore(bigtable): removes cbt source code

### PR DESCRIPTION
**Pull request by telpirion**
CBT development as moved [here](https://github.com/googleapis/cloud-bigtable-cbt-cli).

### CODE REVIEW

**Review by codyoss — APPROVED** [review]
Thanks!

**Review by tritone — COMMENTED** [review]
I noticed that pkg.go.dev still links to google-cloud-go. Is there something that needs to happen to point it to the new location?

**Comment by telpirion** [comment]
> I noticed that pkg.go.dev still links to google-cloud-go. Is there something that needs to happen to point it to the new location?

Good catch. IIRC, @codyoss and I discussed this (but I don't recall what the action item is). Cody, would you mind refreshing my memory as to whether I need to do something special to update pkg.dev.go?

**Comment by codyoss** [comment]
There is likely a little process that is needed to break the chain for deps when carving out a submodule. I have this in a doc internally but there is some external guidance as well. https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository You need to depend on a future version of existing module for a release to break the cycle. Let me know if you wanna chat offline.

**Pull request merged**
