### PR TITLE
chore: update microgen to v0.23.4

### PR DESCRIPTION
**Pull request by noahdietz**
Changes include:
* remove disable service config dial option
* ensure that mix-in protos present in the input file set aren't generated as separate clients when only present for mix-in generation
* dependency updates

### CODE REVIEW

**Comment by noahdietz** [comment]
cc @mohanli-ml

**Review by codyoss — APPROVED** [review]

**Comment by mohanli-ml** [comment]
@noahdietz Hey Noah, when can we expect a new `chore(all): auto-regenerate gapics` PR like #4553, which will actually update the config in spanner_client.go?

**Comment by noahdietz** [comment]
@mohanli-ml yes it runs as a cron job. Check in with @codyoss for updates on that.

**Comment by codyoss** [comment]
@mohanli-ml Another PR should be proposed later this evening.

**Pull request merged**
