### PR TITLE
fix(storage): add content type, disposition and encoding in v4 storage post policy

### LINKED ISSUE #2767: storage: content-type condition does not appear in generated V4 post policy
**Client**

Storage

**Code**

e.g.
```go
opts := &storage.PostPolicyV4Options{
  GoogleAccessID: email,
  PrivateKey:     privateKey,
  Expires:        time.Now().Add(10*time.Minute),
  Fields: &storage.PolicyV4Fields{
    ContentType: "text/plain",
  },
}
googlePolicy, err := storage.GenerateSignedPostPolicyV4(c.config.GoogleUploadBucket, objectKey, opts)
```

**Expected behavior**

The provided `Content-Type` should be included as a condition in the signed policy, per [https://cloud.google.com/storage/docs/xml-api/post-object](https://cloud.google.com/storage/docs/xml-api/post-object).

**Actual behavior**

The provided `Content-Type` is *not* included in the signed policy. Example resulting policy:

```
{
  "URL": "https://storage.googleapis.com/mybucket/",
  "Fields": {
    "key": "myobject",
    "policy": "eyJjb25kaXRpb25zIjpbeyJidWNrZXQiOiJteWJ1Y2tldCJ9LHsia2V5IjoibXlvYmplY3QifSx7IngtZ29vZy1kYXRlIjoiMjAyMDA4MjRUMTAyMjIwWiJ9LHsieC1nb29nLWNyZWRlbnRpYWwiOiJ0ZXN0QGR1bW15LmlhbS5nc2VydmljZWFjY291bnQuY29tLzIwMjAwODI0L2F1dG8vc3RvcmFnZS9nb29nNF9yZXF1ZXN0In0seyJ4LWdvb2ctYWxnb3JpdGhtIjoiR09PRzQtUlNBLVNIQTI1NiJ9XSwiZXhwaXJhdGlvbiI6IjIwMjAtMDgtMjRUMTA6MzI6MjBaIn0=",
    "x-goog-algorithm": "GOOG4-RSA-SHA256",
    "x-goog-credential": "test@dummy.iam.gserviceaccount.com/20200824/auto/storage/goog4_request",
    "x-goog-date": "20200824T102220Z",
    "x-goog-signature": "[redacted]"
  }
}
```

### PR DESCRIPTION
**Pull request by pierreis**
This merge request adds content type, disposition and encoding in storage post policy. These conditions were present in the `PolicyV4Fields`, but ignored.

Fixes #2767.

### CODE REVIEW

**Comment by frankyn** [comment]
Hi @pierreis,

Thanks for finding this gap!

I will need to update our conformance tests to include these fields (https://github.com/googleapis/conformance-tests/tree/master/storage/v1) before we can merge this in.

I'll keep you posted.

After the conformance tests are updated then you'll need to update the following file:

* https://github.com/googleapis/google-cloud-go/blob/master/storage/internal/test/conformance/v4_signatures.json

**Comment by tritone** [comment]
> Hi @pierreis,
> 
> Thanks for finding this gap!
> 
> I will need to update our conformance tests to include these fields (https://github.com/googleapis/conformance-tests/tree/master/storage/v1) before we can merge this in.
> 
> I'll keep you posted.
> 
> After the conformance tests are updated then you'll need to update the following file:
> 
> * https://github.com/googleapis/google-cloud-go/blob/master/storage/internal/test/conformance/v4_signatures.json

Thanks @frankyn . I'm happy to manage getting the conformance test in when you have it ready.

**Comment by tritone** [comment]
I added in the required conformance test. @pierreis could you update this PR to remove the skip here: https://github.com/googleapis/google-cloud-go/blob/master/storage/conformance_test.go#L45 ? Then we can verify that this change makes the conformance test pass.

**Comment by pierreis** [comment]
@tritone Thank you for the updates! I see that you have already pushed the changes 🙂

**Comment by tritone** [comment]
> @tritone Thank you for the updates! I see that you have already pushed the changes 🙂

Yes, I want to get this released soon so figured I'd push it along. :) Thanks again for noticing the issue and sending a PR!

The conformance test is failing currently due to how the conditions are sorted. Following up to see whether the test or the code needs to change here. I should have a fix soon.

**Review by codyoss — APPROVED** [review]
LGTM

**Review by frankyn — APPROVED** [review]

**Review by tritone — APPROVED** [review]

**Pull request merged**
