### PR TITLE
fix(bigtable/bttest): Emulator too lenient for empty RowMutation

### PR DESCRIPTION
**Pull request by jimfulton**
Fixed: #4309

### CODE REVIEW

**Review by garye — APPROVED** [review]
Looks good from bigtable side

**Comment by jimfulton** [comment]
> Looks good from bigtable side

Thanks for the look!

(For some reason, I'm not getting notified for comments on my PRs. :/)

**Review by tritone — APPROVED** [review]

**Comment by jimfulton** [comment]
@tritone I'm not worthy to merge. Can you?

**Review by crwilcox — APPROVED** [review]

**Comment by crwilcox** [comment]
@jimfulton seems a merge conflict arose. Can you address?

**Comment by jimfulton** [comment]
> @jimfulton seems a merge conflict arose. Can you address?

On it!

**Comment by jimfulton** [comment]
> > @jimfulton seems a merge conflict arose. Can you address?
> 
> On it!

Done

**Pull request merged**
