### PR TITLE
feat(logging/logadmin): allow logging PageSize to override

### PR DESCRIPTION
**Pull request by ShubhamRasal**
resolve https://github.com/googleapis/google-cloud-go/issues/5031

This PR, allows user to support custom page size.

### CODE REVIEW

**Review by gkevinzheng — COMMENTED** [review]
Could you add a test for this in `TestListLogEntriesRequest` in `logadmin_test.go`?

**Comment by ShubhamRasal** [comment]
> Could you add a test for this in `TestListLogEntriesRequest` in `logadmin_test.go`?

Hey @gkevinzheng , I've pushed the requested changes. Can you please review it again?

**Comment by gkevinzheng** [comment]
@ShubhamRasal Could you add a test where no option for `PageSize` is set in the `EntriesOption`? I'd like to make sure the change doesn't break existing functionality? It shouldn't, but just in case.

**Comment by ShubhamRasal** [comment]
> @ShubhamRasal Could you add a test where no option for `PageSize` is set in the `EntriesOption`? I'd like to make sure the change doesn't break existing functionality? It shouldn't, but just in case.

To address your concern, I want to clarify that the scenario you mentioned is indeed covered by our existing test suite. Initially, our test cases were designed without explicitly naming the variables, leading us to use `0` as a default value for `PageSize` in all tests to simulate the absence of this option.

However, recognizing the importance of readability and ease of contribution, I have recently revisited and updated our test cases. These updates aim to make the test intentions clearer and the overall tests more contributor-friendly. During this process, I also identified and removed a duplicate test case.
image (6)

I hope these adjustments effectively address your concern. Please let me know if there are any further adjustments or clarifications you would recommend.
@gkevinzheng

**Review by gkevinzheng — APPROVED** [review]

**Pull request merged**
