### PR TITLE
test: start building all code

### PR DESCRIPTION
**Pull request by codyoss**
Code is built when testing it, but some type of build failures are
not properly translated by the junit converter we use. Adding this
extra build will catch this previously missed failures and should
affect test time minimally as builds will have been cached.

Fixes: #6439

### CODE REVIEW

**Review by quartzmo — APPROVED** [review]

**Comment by quartzmo** [comment]
Kokoro:

```
+ cat sponge_log.log
+ go-junit-report -set-exit-code
+ exit_code=2
+ go build ./...
/tmpfs/src/google-cloud-go
+ exit_code=2
```

**Comment by codyoss** [comment]
Haha OOMed the machine for trying to build the snippet directory. I will add a check for skipping the building of that one

**Comment by noahdietz** [comment]
> 

Would it make sense to add a build tag to snippet files?

**Comment by codyoss** [comment]
@noahdietz My only fear there is that the code is less copy pastable. I think tags are pretty advanced and users that drill into the sample and copy the whole file may be confused why `go run/go bulid` is not just working without removing the magic comment

**Comment by noahdietz** [comment]
> @noahdietz My only fear there is that the code is less copy pastable. I think tags are pretty advanced and users that drill into the sample and copy the whole file may be confused why `go run/go bulid` is not just working without removing the magic comment

That's fair! No need to then.

**Pull request merged**
