### PR TITLE
fix(vertexai): bump deps to fix build error

### PR DESCRIPTION
**Pull request by codyoss**
Tested locally to make sure it works.

Fixes: #9167

### CODE REVIEW

**Comment by codyoss** [comment]
As a side note to @eliben @jba I don't understand why go build did not catch this... Does it have to do with the module workspace or am I missing something?

**Review by noahdietz — APPROVED** [review]

**Comment by eliben** [comment]
> As a side note to @eliben @jba I don't understand why go build did not catch this... Does it have to do with the module workspace or am I missing something?

The root repo has a `go.work` file, which will mask such issues. This is the reason why having a `go.work` file committed is considered dangerous; when it's committed, it's worth at least running the tests with `GOWORK=off` to catch such issues.

You can try to run all tests in this repo with `GOWORK=off` in CI - this may uncover surprises :)

**Comment by codyoss** [comment]
> This is the reason why having a go.work file committed is considered dangerous

I never got this impression when reading docs. Is this written anywhere?

> You can try to run all tests in this repo with GOWORK=off

Will file an issue, thanks

**Comment by eliben** [comment]
> > This is the reason why having a go.work file committed is considered dangerous
> 
> I never got this impression when reading docs. Is this written anywhere?
>

I'll reply in #9170

**Pull request merged**
