### PR TITLE
feat(logging)!: increase DefaultEntryByteThreshold to 8Mb

### PR DESCRIPTION
**Pull request by nicoleczhu**
Fixes: #3823 

DefaultEntryByteThreshold = `1 << 20 // 1MiB` ===> `1 << 23 // 8MiB` since size of an entries.write request	can be up to 10 MB. 

`DefaultBufferedByteLimit` is unchanged as that's more a cap on memory utilization.

### CODE REVIEW

**Comment by nicoleczhu** [comment]
@loburm mind sanity checking this? I think changing default thresholds may produce unforeseen results, so we might want to release this with preview

**Review by simonz130 — APPROVED** [review]

**Comment by loburm** [comment]
In overall it looks good to me.

**Comment by nicoleczhu** [comment]
@codyoss can I get your pointers, this PR is marked as a breaking change in go116 because: 
```
The following breaking changes were found:
cloud.google.com/go/logging:
- DefaultEntryByteThreshold: value changed from 1048576 to 8388608
```

It's technically not since we're increasing the threshold, not decreasing it. How do I override this, or fix this test? Thank you!

**Comment by codyoss** [comment]
It is a breaking change. I silly example is if someone wrote a test validate its value, or grabbed an element of an array at this index, which could panic if the array was not large enough. That being said I with proper usage I think this is probably fine ... @tbpg would you agree?

To get around this check the commit message needs to be formatted in a special manner: https://github.com/googleapis/google-cloud-go/blob/00140bde9fc18d3ac21ea717df4aff8ed8db2262/internal/apidiff/apidiff.go#L223-L238

Also, the subsequent release would need to be manual overridden as it will propose a v2.

**Pull request merged**
