### PR TITLE
feat(spanner/spansql): support fine-grained access control DDL syntax

### PR DESCRIPTION
**Pull request by nktks**
This PR supports [fine-grained access control](https://cloud.google.com/spanner/docs/fgac-about) DDL syntax parsing.
- `CREATE ROLE`
- `DROP ROLE`
- `GRANT`
- `REVOKE`

### CODE REVIEW

**Comment by rahul2393** [comment]
Thanks @nktks for this, please fix the conflicts.

**Comment by nktks** [comment]
@rahul2393 Thank you! I fixed conflict and following function name change.

**Comment by toga4** [comment]
Are there any obstacles other than conflicts in proceeding with this PR?
We are waiting for this PR to be merged.

**Comment by nktks** [comment]
@toga4 Thanks for your reminding.

I fixed conflicts and modified code not to change exist func name (like `parseCommaList`, `parseTableOrIndexOrColumnName`, `parseColumnNameList`) for avoiding compile error when other PR's changes include these function.

@rahul2393 Could you please take a look this PR?

Thank you!

**Review by rahul2393 — APPROVED** [review]

**Pull request merged**
