### PR TITLE
docs(datastore): replace depricated func in docs

### LINKED ISSUE #8638: datastore: The reference implementation in the documentation uses a depricated function `Query.Filter`
Related Issue: #6725

The [datastore documentation](https://pkg.go.dev/cloud.google.com/go/datastore@v1.14.0) uses a depricated function ( `Query.Filter` ).
It should be fixed to `FilterField` as new users will use `Filter` by reference to it.

In addition to what was pointed out in the related Issue( #6725 ) , there are other points that should be fixed as follows

- https://github.com/googleapis/google-cloud-go/blob/5feb3eaa2a73b147f7858b5c91c59315a914b344/datastore/example_test.go#L274
- https://github.com/googleapis/google-cloud-go/blob/5feb3eaa2a73b147f7858b5c91c59315a914b344/datastore/doc.go#L223

### PR DESCRIPTION
**Pull request by takanakahiko**
fix #8638

### CODE REVIEW

**Review by bhshkh — APPROVED** [review]

**Comment by bhshkh** [comment]
This branch is out-of-date with the base branch. Please update the branch.

**Comment by bhshkh** [comment]
Please allow edits.
https://github.com/googleapis/google-cloud-go/blob/6e7761183a53189470f30d72a7474128f11f6dd0/CONTRIBUTING.md?plain=1#L40

**Comment by takanakahiko** [comment]
@bhshkh 
I checked `Always suggest updating pull request branches`

**Comment by bhshkh** [comment]
I do not have edit access. Please grant edit access. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by bhshkh** [comment]
I have run the workflows but now since the branch is out of date, it cannot be merged even though the workflows passed. Now, I do not have access to update the branch.

When author updates the branch, the workflows will need to be approved and run again by me. If workflows are not run immediately after updating the branch, the branch CANNOT be merged.

So, I need edit access to update the branch and then immediately approve and run the workflows.

**Comment by takanakahiko** [comment]
When a PR is sent from an organization, "Allow edits by maintainers" appears to be disabled. Fork to your personal repository and recreate the PR.
https://github.com/orgs/community/discussions/5634

**Comment by takanakahiko** [comment]
@bhshkh Created a new PR #8989

**Pull request closed without merging**
