### PR TITLE
chore(internal/generated/snippets): upgrade dependencies

### PR DESCRIPTION
**Pull request by quartzmo**

### CODE REVIEW

**Review by codyoss — APPROVED** [review]
This is fine, but most if not all of these should have replace directives that override what code is actually being run. This is how we can have samples for unreleased code.

**Comment by quartzmo** [comment]
> most if not all of these should have replace directives that override what code is actually being run

Right, my main objective with this PR is to see if the kokoro build errors we saw yesterday in #6523 occur in a new branch off main.

**Comment by quartzmo** [comment]
Even though the build passes, I still see the errors below in the kokoro [latest](https://source.cloud.google.com/results/invocations/1abd8cfa-8bf3-4789-a29c-0ecee85a0db6/log) log:

@codyoss Does this suggest that there are orphaned snippet files (such as `CreateSnapshotSchedulePolicy/main.go`) that need to be cleaned up?

```
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/CreateSnapshotSchedulePolicy
baremetalsolution/apiv2/Client/CreateSnapshotSchedulePolicy/main.go:36:30: undefined: baremetalsolution.CreateSnapshotSchedulePolicyRequest
baremetalsolution/apiv2/Client/CreateSnapshotSchedulePolicy/main.go:40:17: c.CreateSnapshotSchedulePolicy undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method CreateSnapshotSchedulePolicy)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/CreateVolumeSnapshot
baremetalsolution/apiv2/Client/CreateVolumeSnapshot/main.go:36:30: undefined: baremetalsolution.CreateVolumeSnapshotRequest
baremetalsolution/apiv2/Client/CreateVolumeSnapshot/main.go:40:17: c.CreateVolumeSnapshot undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method CreateVolumeSnapshot)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/DeleteSnapshotSchedulePolicy
baremetalsolution/apiv2/Client/DeleteSnapshotSchedulePolicy/main.go:36:30: undefined: baremetalsolution.DeleteSnapshotSchedulePolicyRequest
baremetalsolution/apiv2/Client/DeleteSnapshotSchedulePolicy/main.go:40:10: c.DeleteSnapshotSchedulePolicy undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method DeleteSnapshotSchedulePolicy)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/DeleteVolumeSnapshot
baremetalsolution/apiv2/Client/DeleteVolumeSnapshot/main.go:36:30: undefined: baremetalsolution.DeleteVolumeSnapshotRequest
baremetalsolution/apiv2/Client/DeleteVolumeSnapshot/main.go:40:10: c.DeleteVolumeSnapshot undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method DeleteVolumeSnapshot)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/GetSnapshotSchedulePolicy
baremetalsolution/apiv2/Client/GetSnapshotSchedulePolicy/main.go:36:30: undefined: baremetalsolution.GetSnapshotSchedulePolicyRequest
baremetalsolution/apiv2/Client/GetSnapshotSchedulePolicy/main.go:40:17: c.GetSnapshotSchedulePolicy undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method GetSnapshotSchedulePolicy)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/GetVolumeSnapshot
baremetalsolution/apiv2/Client/GetVolumeSnapshot/main.go:36:30: undefined: baremetalsolution.GetVolumeSnapshotRequest
baremetalsolution/apiv2/Client/GetVolumeSnapshot/main.go:40:17: c.GetVolumeSnapshot undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method GetVolumeSnapshot)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/ListSnapshotSchedulePolicies
baremetalsolution/apiv2/Client/ListSnapshotSchedulePolicies/main.go:37:30: undefined: baremetalsolution.ListSnapshotSchedulePoliciesRequest
baremetalsolution/apiv2/Client/ListSnapshotSchedulePolicies/main.go:41:10: c.ListSnapshotSchedulePolicies undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method ListSnapshotSchedulePolicies)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/ListVolumeSnapshots
baremetalsolution/apiv2/Client/ListVolumeSnapshots/main.go:37:30: undefined: baremetalsolution.ListVolumeSnapshotsRequest
baremetalsolution/apiv2/Client/ListVolumeSnapshots/main.go:41:10: c.ListVolumeSnapshots undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method ListVolumeSnapshots)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/RestoreVolumeSnapshot
baremetalsolution/apiv2/Client/RestoreVolumeSnapshot/main.go:36:30: undefined: baremetalsolution.RestoreVolumeSnapshotRequest
baremetalsolution/apiv2/Client/RestoreVolumeSnapshot/main.go:40:15: c.RestoreVolumeSnapshot undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method RestoreVolumeSnapshot)
# cloud.google.com/go/internal/generated/baremetalsolution/apiv2/Client/UpdateSnapshotSchedulePolicy
baremetalsolution/apiv2/Client/UpdateSnapshotSchedulePolicy/main.go:36:30: undefined: baremetalsolution.UpdateSnapshotSchedulePolicyRequest
baremetalsolution/apiv2/Client/UpdateSnapshotSchedulePolicy/main.go:40:17: c.UpdateSnapshotSchedulePolicy undefined (type *"cloud.google.com/go/baremetalsolution/apiv2".Client has no field or method UpdateSnapshotSchedulePolicy)
# cloud.google.com/go/internal/generated/contactcenterinsights/apiv1/Client/CancelOperation
contactcenterinsights/apiv1/Client/CancelOperation/main.go:40:10: c.CancelOperation undefined (type *"cloud.google.com/go/contactcenterinsights/apiv1".Client has no field or method CancelOperation)
# cloud.google.com/go/internal/generated/contactcenterinsights/apiv1/Client/GetOperation
contactcenterinsights/apiv1/Client/GetOperation/main.go:40:17: c.GetOperation undefined (type *"cloud.google.com/go/contactcenterinsights/apiv1".Client has no field or method GetOperation)
# cloud.google.com/go/internal/generated/contactcenterinsights/apiv1/Client/ListOperations
contactcenterinsights/apiv1/Client/ListOperations/main.go:41:10: c.ListOperations undefined (type *"cloud.google.com/go/contactcenterinsights/apiv1".Client has no field or method ListOperations)
# cloud.google.com/go/internal/generated/servicemanagement/apiv1/ServiceManagerClient/DisableService
servicemanagement/apiv1/ServiceManagerClient/DisableService/main.go:36:30: undefined: servicemanagement.DisableServiceRequest
servicemanagement/apiv1/ServiceManagerClient/DisableService/main.go:40:15: c.DisableService undefined (type *"cloud.google.com/go/servicemanagement/apiv1".ServiceManagerClient has no field or method DisableService)
# cloud.google.com/go/internal/generated/servicemanagement/apiv1/ServiceManagerClient/EnableService
servicemanagement/apiv1/ServiceManagerClient/EnableService/main.go:36:30: undefined: servicemanagement.EnableServiceRequest
servicemanagement/apiv1/ServiceManagerClient/EnableService/main.go:40:15: c.EnableService undefined (type *"cloud.google.com/go/servicemanagement/apiv1".ServiceManagerClient has no field or method EnableService)
```

**Comment by codyoss** [comment]
@quartzmo Yeah lets just get those cleaned up here to. From prior breaking changes that have removed things. snipetgen is only additive today, it will not remove orphaned snippets. This may be a good enhancement for the future.

**Comment by quartzmo** [comment]
/cc @noahdietz

> snipetgen is only additive today, it will not remove orphaned snippets. This may be a good enhancement for the future.

**Review by noahdietz — APPROVED** [review]

**Pull request merged**
