### PR TITLE
fix(auth): make default client creation more lenient

### PR DESCRIPTION
**Pull request by hslatman**
Before this commit, `CloneDefaultClient` would panic if `http.DefaultTransport`
was set to something that's not an `*http.Transport`. It is very much possible
that this is the case if users assign a different `http.RoundTripper` to
`http.DefaultTransport`, for example for tracing purposes.

This commit renames `CloneDefaultClient` to `DefaultClient`, and changes its
behavior to check if the `http.DefaultTransport` can be cloned, and uses the
clone if possible. If it can't be cloned, it'll use the `http.DefaultTransport`
directly.

Fixes: #10638

### CODE REVIEW

**Comment by quartzmo** [comment]
I'm not sure why apidiff for `aiplatform` is failing for this PR. Please update this branch in any case.

**Comment by hslatman** [comment]
@quartzmo I've rebased it. Figured it'd be cleaner than the merge, since it's just a single commit.

**Review by codyoss — APPROVED** [review]

**Comment by quartzmo** [comment]
@hslatman Kokoro CI build failed. I see this error in the tests:

```
➜  auth git:(fix-auth-http-transport-clone) go test ./...
# cloud.google.com/go/auth/credentials/internal/externalaccount [cloud.google.com/go/auth/credentials/internal/externalaccount.test]
credentials/internal/externalaccount/externalaccount_test.go:480:21: undefined: internal.CloneDefaultClient
credentials/internal/externalaccount/x509_provider_test.go:60:22: undefined: internal.CloneDefaultClient
ok  	cloud.google.com/go/auth	0.998s
FAIL	cloud.google.com/go/auth/credentials/internal/externalaccount [build failed]
```

**Comment by codyoss** [comment]
It looks like a couple of `CloneDefaultClient` were missed.

**Comment by hslatman** [comment]
@quartzmo yes, I noticed too. There were some calls to `CloneDefaultClient`. I guess those were added in some of the most recent commits that I rebased on, and I didn't check before pushing again 😅

**Comment by quartzmo** [comment]
Thank you for your contribution @hslatman!

**Pull request merged**
