### PR TITLE
fix(all): Update hand-written clients to not use WithEndpoint override

### PR DESCRIPTION
**Pull request by andyrzhao**
-logging clients delegate to the gapic generated client with the correct defaults, so no need to override.
-bigtable and spanner clients needs to be manually updated to use DefaultEndpoint and DefaultMTLSEndpoint

### CODE REVIEW

**Comment by hengfengli** [comment]
For Spanner, it looks good to me. 👍

**Review by tritone — COMMENTED** [review]
Looks fine to me for bigtable. @kolea2 can you take a look as well?

**Review by codyoss — COMMENTED** [review]
LGTM, but I'll wait to approve until other sub-module owners have a chance to see the changes. Note these changes already happened for all other currently generating gapic clients. This is a cleanup task to update the manual layers.

**Review by nicoleczhu — APPROVED** [review]
Logging LGTM

**Review by codyoss — APPROVED** [review]

**Pull request merged**
