### PR TITLE
test(spanner): fix the failed TestColumnTypeErr test

### LINKED ISSUE #4443: spanner: TestColumnTypeErr failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: f6258a47a4dfadc02dcdd75b53fd5f88c5dcca30
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/45f41c12-86f2-46aa-bace-8c12b62407af), [Sponge](http://sponge2/45f41c12-86f2-46aa-bace-8c12b62407af)
status: failed
<details><summary>Test output</summary><br><pre>row_test.go:421: Column(28): decoding into destination with wrong type *struct {} returns error spanner: code = "InvalidArgument", desc = "failed to decode column 28, error = <the container is not a slice of struct pointers: spanner: code = \"InvalidArgument\", desc = \"type *struct {} cannot be used for decoding ARRAY[STRUCT]\">", want spanner: code = "InvalidArgument", desc = "failed to decode column 28, type *struct {} cannot be used for decoding ARRAY[STRUCT]"
row_test.go:425: ColumnByName(STRUCT_ARRAY): decoding into destination with wrong type *struct {} returns error spanner: code = "InvalidArgument", desc = "failed to decode column 28, error = <the container is not a slice of struct pointers: spanner: code = \"InvalidArgument\", desc = \"type *struct {} cannot be used for decoding ARRAY[STRUCT]\">", want spanner: code = "InvalidArgument", desc = "failed to decode column 28, type *struct {} cannot be used for decoding ARRAY[STRUCT]"
row_test.go:421: Column(29): decoding into destination with wrong type *struct {} returns error spanner: code = "InvalidArgument", desc = "failed to decode column 29, error = <the container is not a slice of struct pointers: spanner: code = \"InvalidArgument\", desc = \"type *struct {} cannot be used for decoding ARRAY[STRUCT]\">", want spanner: code = "InvalidArgument", desc = "failed to decode column 29, type *struct {} cannot be used for decoding ARRAY[STRUCT]"
row_test.go:425: ColumnByName(NULL_STRUCT_ARRAY): decoding into destination with wrong type *struct {} returns error spanner: code = "InvalidArgument", desc = "failed to decode column 29, error = <the container is not a slice of struct pointers: spanner: code = \"InvalidArgument\", desc = \"type *struct {} cannot be used for decoding ARRAY[STRUCT]\">", want spanner: code = "InvalidArgument", desc = "failed to decode column 29, type *struct {} cannot be used for decoding ARRAY[STRUCT]"</pre></details>

### PR DESCRIPTION
**Pull request by hengfengli**
Fix #4443

### CODE REVIEW

**Comment by hengfengli** [comment]
@olavloite I wonder why the previous CI tests did not catch this error. It may be due to caching the test results.

**Comment by olavloite** [comment]
> @olavloite I wonder why the previous CI tests did not catch this error. It may be due to caching the test results.

Yes, that is very strange. I looked into the log of the build for the PR, and the test failed in that build as well, but the build is marked as green: https://source.cloud.google.com/results/invocations/1e012eba-5a8c-4681-9a59-919f7ec7e1d3/targets/cloud-devrel%2Fclient-libraries%2Fgo%2Fgoogle-cloud-go%2Fpresubmit%2Fgo111/log (search for `TestColumnTypeErr` in the log output).
It worries me that the CI can mark a build as green while there are test failures. Do you know who could best look into that?

**Comment by olavloite** [comment]
@hengfengli If you take a look at the Kokoro build log for this build as well, you will see that there is a test failure there as well:

```
=== RUN   TestRowToString
--- FAIL: TestRowToString (0.00s)
    row_test.go:1693: got {fields: [name:"F1"  type:{code:STRING} name:"F2"  type:{code:STRING}], values: [string_value:"v1" string_value:"v2"]}, want {fields: [name:"F1" type:{code:STRING} name:"F2" type:{code:STRING}], values: [string_value:"v1" string_value:"v2"]}
```

@codyoss Is this a known issue? We are getting green builds from kokoro while there are test failures.

**Comment by hengfengli** [comment]
> @hengfengli If you take a look at the Kokoro build log for this build as well, you will see that there is a test failure there as well:
> 
> ```
> === RUN   TestRowToString
> --- FAIL: TestRowToString (0.00s)
>     row_test.go:1693: got {fields: [name:"F1"  type:{code:STRING} name:"F2"  type:{code:STRING}], values: [string_value:"v1" string_value:"v2"]}, want {fields: [name:"F1" type:{code:STRING} name:"F2" type:{code:STRING}], values: [string_value:"v1" string_value:"v2"]}
> ```

It is the whitespaces between `name` and `type`. Sometime, it gets two spaces and sometimes it gets a single space. I tested it locally and the test passes. Do you have any suggestion on how to verify this?

**Comment by olavloite** [comment]
> > @hengfengli If you take a look at the Kokoro build log for this build as well, you will see that there is a test failure there as well:
> > ```
> > === RUN   TestRowToString
> > --- FAIL: TestRowToString (0.00s)
> >     row_test.go:1693: got {fields: [name:"F1"  type:{code:STRING} name:"F2"  type:{code:STRING}], values: [string_value:"v1" string_value:"v2"]}, want {fields: [name:"F1" type:{code:STRING} name:"F2" type:{code:STRING}], values: [string_value:"v1" string_value:"v2"]}
> > ```
> 
> @olavloite It is the whitespaces between `name` and `type`. Sometime, it gets two spaces and sometimes it gets a single space. I tested it locally and the test passes. Do you have any suggestion on how to verify this? Or, maybe I can just delete this test.

@hengfengli It's cause by [this line](https://github.com/protocolbuffers/protobuf-go/blob/b03064a95cacfede187231741d9918a75653057d/internal/encoding/text/encode.go#L228) which will add an additional space based on a deterministically random boolean value. So you could call `if detrand.Bool()` in the test to determine whether the string will/should contain 2 spaces or not.

**Comment by codyoss** [comment]
@olavloite Thanks for bringing this to my attention this is a bug I was unaware of. Will try to get out a fix today.

**Comment by hengfengli** [comment]
> if detrand.Bool()

@olavloite "google.golang.org/protobuf/internal/detrand" is an internal package. I can't use it in my code. I did it in a different way, PTAL.

**Review by olavloite — APPROVED** [review]

**Comment by olavloite** [comment]
> > if detrand.Bool()
> 
> @olavloite "google.golang.org/protobuf/internal/detrand" is an internal package. I can't use it in my code. I did it in a different way, PTAL.

Sorry, I didn't notice that it was an internal package. Your alternative solution looks good to me.

**Comment by hengfengli** [comment]
@skuruppu Can I get an approval from you? Thanks.

**Review by codyoss — APPROVED** [review]
LGTM

**Comment by codyoss** [comment]
Merging this to fix CI.

**Pull request merged**
