### PR TITLE
feat(bigquery): expose ProjectID from Client & Job

### PR DESCRIPTION
**Pull request by derekperkins**
As more and more BigQuery features like BI Engine, Reservations, etc. are opt-in at a project level only, we are now using more dependency injection for multiple clients. As currently written, we have to create a throwaway dataset from the client to expose the project associated with the client and keep track of that separately to map to any jobs. The project is trivially available from both the client and job, so this PR exposes both.

### CODE REVIEW

**Comment by derekperkins** [comment]
@shollyman @codyoss Any chance this could make it into the 1.19 release?

**Review by shollyman — APPROVED** [review]
Thanks.  This seems reasonable to expose.  I've also created https://github.com/googleapis/google-cloud-go/issues/4228 for myself to come back through and improve job reference construction.

**Comment by shollyman** [comment]
Feedback from others was we should consider whether we should simply change to exported variables.  Primary issue is still the retained context; need to take a closer look at this to see if we want to open it up rather than simply exposing functions as laid out here.

**Comment by derekperkins** [comment]
For reference, ProjectID is exported in Dataset. I don't particularly care whether ProjectID is exported or whether it is exposed with a function to protect the integrity of the object. I just worry that taking a closer look will cause this to end up in the backlog.

https://github.com/googleapis/google-cloud-go/blob/22344f085efd0573a1f9d5904e4f430e2a4d718d/bigquery/dataset.go#L30-L31

**Comment by shollyman** [comment]
Closing this PR, functionality was added in https://github.com/googleapis/google-cloud-go/pull/4312.  Thanks for bringing it to my attention, ended up highlighting the autodetection gap.

**Comment by derekperkins** [comment]
Thanks for making that happen, much appreciated

**Pull request closed without merging**
