### PR TITLE
fix(spanner): remove session handle lock during dumping the tracked session handles.

### PR DESCRIPTION
**Pull request by yfuruyama**
Fixes https://github.com/googleapis/google-cloud-go/issues/5710.

### CODE REVIEW

**Comment by rahul2393** [comment]
I tried running this snippet with "go run -race ." https://go.dev/play/p/VV1SeNJfjq6 which is reading a shard object like sessionHandle and has list.Element just as we have trackedSessionHandle, it reports data race, and if I add lock in read the warning goes away. @olavloite Do you think its good idea to remove lock here.

**Comment by olavloite** [comment]
I don't think it's a good idea to remove taking the lock there. Even though we don't change it there, Go will detect a data race if were are trying to read it while it is being changed by another goroutine. And that could happen if for example the session is returned to the session pool while we are reading it here.

**Comment by yfuruyama** [comment]
Yeah I realized that `stack` is a slice and it could be modified while reading the slice. So this is not a good idea.

Then what we can do would be changing the order of two mutex locking to fix the [current lock order](https://github.com/googleapis/google-cloud-go/issues/5710#issuecomment-1063799494). Is it feasible?

**Comment by rahul2393** [comment]
I would rather try RWMutex if it helps here avoid the deadlock, @yfuruyama were you able to replicate the issue, if yes can you share the script?

**Comment by yfuruyama** [comment]
@rahul2393 I pasted a code snippet in an original issue: https://github.com/googleapis/google-cloud-go/issues/5710#issuecomment-1066255978 Let's discuss in that thread.

**Comment by rahul2393** [comment]
Closing, will be fixed via https://github.com/googleapis/google-cloud-go/pull/5777

**Pull request closed without merging**
