### PR TITLE
chore: update import paths in manual layers

### PR DESCRIPTION
**Pull request by codyoss**
Updates: #7233

### CODE REVIEW

**Comment by robfig** [comment]
I was also running into this issue - your commit fixed some of it, but I'm also encountering other usages of the old pb path in /logging, e.g.
```
external/com_google_cloud_go_logging/apiv2/config_client.go:1158:55: cannot use resp (variable of type *"google.golang.org/genproto/googleapis/longrunning".Operation) as type *longrunningpb.Operation in argument to longrunning.InternalNewOperation
```

Looks like the import is still the old one at HEAD:
```
	longrunningpb "google.golang.org/genproto/googleapis/longrunning"
```
https://github.com/googleapis/google-cloud-go/blob/main/logging/apiv2/config_client.go#L34

Should there be a repo-wide find-replace, or am I misunderstanding? 
Thanks!

**Comment by codyoss** [comment]
@robfig As long as you are using a newer version of the genproto library this should not be an issue. This is mostly a cosmetic change in the code.

**Comment by codyoss** [comment]
But yes, more locations likely can be updated as well and will be.

**Review by quartzmo — APPROVED** [review]

**Comment by quartzmo** [comment]
@robfig Here is the alias for `Operation` in the latest `go-genproto` from `google.golang.org/genproto/googleapis/longrunning` to `cloud.google.com/go/longrunning/autogen/longrunningpb`: https://github.com/googleapis/go-genproto/blob/main/googleapis/longrunning/alias.go#L70

**Pull request merged**
