### PR TITLE
test(spanner): fix race when accessing trace spans

### LINKED ISSUE #10141: spanner: TestClient_DoForEachRow_ShouldEndSpanWithQueryError failed
Note: #5005 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 11e1334d16fa069f601d8f08217ddd3f4fdb9a95
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/031190a2-4277-482c-aff2-522bc4377597), [Sponge](http://sponge2/031190a2-4277-482c-aff2-522bc4377597)
status: failed

### LINKED ISSUE #10184: spanner: TestClient_BatchWrite_SpanExported failed
Note: #10114 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 71a093a9391df5a7e51532d6cdbfa751fbd6dd1e
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/12797fa4-6386-4efc-92dd-48e026268a33), [Sponge](http://sponge2/12797fa4-6386-4efc-92dd-48e026268a33)
status: failed

### PR DESCRIPTION
**Pull request by itizir**
Closes #10184, closes #10141.
Continuation of #5006.
Noticed in pipeline for #10153.

### CODE REVIEW

**Review by rahul2393 — APPROVED** [review]

**Comment by itizir** [comment]
Ah, thanks for fixing it up! Sorry I missed those spots…

**Comment by itizir** [comment]
It's probably fine to return the pointer to the span data itself. What I'm not sure about is whether checking that there is _no more_ than 1 span in that trace test is important... Let me know if you want me to tweak that some more, or feel free to do as you wish. :)

**Review by quartzmo — APPROVED** [review]

**Comment by quartzmo** [comment]
kokoro failure:

```
# cloud.google.com/go/bigquery [cloud.google.com/go/bigquery.test]
./oc_test.go:35:9: invalid operation: cannot call non-function te.Spans (variable of type []*"go.opencensus.io/trace".SpanData)
FAIL	cloud.google.com/go/bigquery [build failed]
?   	cloud.google.com/go/bigquery/analyticshub/apiv1/analyticshubpb	[no test files]
?   	cloud.google.com/go/bigquery/biglake/apiv1/biglakepb	[no test files]
```

**Comment by rahul2393** [comment]
> kokoro failure:
> 
> ```
> # cloud.google.com/go/bigquery [cloud.google.com/go/bigquery.test]
> ./oc_test.go:35:9: invalid operation: cannot call non-function te.Spans (variable of type []*"go.opencensus.io/trace".SpanData)
> FAIL	cloud.google.com/go/bigquery [build failed]
> ?   	cloud.google.com/go/bigquery/analyticshub/apiv1/analyticshubpb	[no test files]
> ?   	cloud.google.com/go/bigquery/biglake/apiv1/biglakepb	[no test files]
> ```

Yes, we need to first release the changes in cloud.google.com/go after which we need to make other relevant changes.

**Comment by harshachinta** [comment]
@rahul2393 I guess the PR title should be changed to `internal` instead of `spanner` for the release in that module. Also does `test` create a new release or should it be tagged as `fix`?

**Pull request merged**
