### PR TITLE
chore(all): release v0.63.0

### PR DESCRIPTION
**Pull request by bcoe**
:robot: I have created a release \*beep\* \*boop\* 
---
### Features

* **all:** auto-regenerate gapics ([#2682](https://www.github.com/googleapis/google-cloud-go/issues/2682)) ([63bfd63](https://www.github.com/googleapis/google-cloud-go/commit/63bfd638da169e0f1f4fa4a5125da2955022dc04))
* **analytics/admin:** start generating apiv1alpha ([#2670](https://www.github.com/googleapis/google-cloud-go/issues/2670)) ([268199e](https://www.github.com/googleapis/google-cloud-go/commit/268199e5350a64a83ecf198e0e0fa4863f00fa6c))
* **functions/metadata:** Special-case marshaling ([#2669](https://www.github.com/googleapis/google-cloud-go/issues/2669)) ([d8d7fc6](https://www.github.com/googleapis/google-cloud-go/commit/d8d7fc66cbc42f79bec25fb0daaf53d926e3645b))
* **gaming:** start generate apiv1 ([#2681](https://www.github.com/googleapis/google-cloud-go/issues/2681)) ([1adfd0a](https://www.github.com/googleapis/google-cloud-go/commit/1adfd0aed6b2c0e1dd0c575a5ec0f49388fa5601))
* **internal/kokoro:** add script to test compatibility with samples ([#2637](https://www.github.com/googleapis/google-cloud-go/issues/2637)) ([f2aa76a](https://www.github.com/googleapis/google-cloud-go/commit/f2aa76a0058e86c1c33bb634d2c084b58f77ab32))
---

This PR was generated with [Release Please](https://github.com/googleapis/release-please).

### CODE REVIEW

**Comment by broady** [comment]
Hmm. Occurs to me we might need to make the bot module aware. Or is it already?

**Comment by codyoss** [comment]
It is not module aware, just iterating on the main module right now.

**Comment by bcoe** [comment]
@broady for folks following a long (or who want to help figure out the first pass):

https://github.com/googleapis/release-please/pull/514

@codyoss and I just did an hour spike on the work.

**Comment by codyoss** [comment]
For now I am going to merge this. If we are not happy with the formatting this generated please comment on the PR listed above. We can always update this retroactively. 

I am merging this to test how auto-release handles the PR. It should tag this commit for us once merged.

**Comment by codyoss** [comment]
On second thought I will be manually tagging this one as we don't have configuration [here](https://github.com/googleapis/releasetool/tree/b32d6e5e204d76ff8719aa9c2609b0dea4056e52/releasetool/commands/tag)

**Pull request merged**
