### PR TITLE
chore(spanner): trigger a release for low cost instance

### PR DESCRIPTION
**Pull request by hengfengli**
Release-As: 1.21.0

Trigger release for low cost instance.

### CODE REVIEW

**Comment by hengfengli** [comment]
@codyoss Can this trigger a new release? Or should I do something like https://github.com/googleapis/google-cloud-go/pull/4002?

**Comment by codyoss** [comment]
@hengfengli You will need to make sure the `Release-As: 1.XX.0` shows up in the merged commit. Chores do not trigger releases otherwiese -- just feats and fixes.

**Comment by hengfengli** [comment]
Please do not merge at the moment. I am waiting for an approval from the backend team.

**Comment by hengfengli** [comment]
@codyoss Can you approve this PR? Thanks.

**Review by codyoss — APPROVED** [review]

**Pull request merged**
