### PR TITLE
feat(spanner): allow configuring batch timeout property in session client

### PR DESCRIPTION
**Pull request by n0npax**
Fixes: https://github.com/googleapis/google-cloud-go/issues/7964

Creating NewClientWithConfig supports the BatchTimeout property.

### CODE REVIEW

**Review by rahul2393 — APPROVED** [review]

**Comment by rahul2393** [comment]
@n0npax  please fix the vet issues

**Comment by n0npax** [comment]
vet was complaining on some stuff which imo look unrelated.
Applied changes from `vet.sh` to the code. Can you pls re-review @rahul2393

**Comment by n0npax** [comment]
Screenshot 2023-05-23 at 5 29 23 pm

yay, `vet` is green now :) Can I ask for `kokoro` run please

**Comment by n0npax** [comment]
conflicts resolved, can I ask for CI/CD run and merge, please?

**Comment by n0npax** [comment]
@rahul2393 can I please ask for CI pipeline re-run?

**Comment by n0npax** [comment]
@rahul2393 can I ask for ‘Kokoro’ and merge please?

**Comment by n0npax** [comment]
Thank you 🚀

**Pull request merged**
