### PR TITLE
feat(storage): add missing StorageClass in BucketAttrsToUpdate

### PR DESCRIPTION
**Pull request by AlisskaPie**

### CODE REVIEW

**Review by tritone — APPROVED** [review]
Looks good to me! Will merge when you stamp @frankyn

**Comment by AlisskaPie** [comment]
Gentle ping

**Comment by tbpg** [comment]
@tritone @frankyn, are we good to merge this?

**Review by frankyn — APPROVED** [review]

**Comment by frankyn** [comment]
Apologies for the lag here, totally missed this.

**Pull request merged**
