### PR TITLE
fix(bigquery/storage/managedwriter): address possible resource leak

### PR DESCRIPTION
**Pull request by shollyman**
This PR ensures getStream() is responsible for closing the existing connection and pending write channel if present.

Fixes: https://github.com/googleapis/google-cloud-go/issues/6766

### CODE REVIEW

**Review by fsaintjacques — APPROVED** [review]
LGTM, thank you @shollyman for the quick turn-around, will you be able to cut a release soon?

**Comment by shollyman** [comment]
@fsaintjacques regarding releasing, that's a little challenging for the next couple weeks.  We'll be pausing releases during the runup to this year's Google Next event (Oct 11-13), and should resume normal releasing afterwards.  There's a [number of changes](https://github.com/googleapis/google-cloud-go/pull/6730) that will be part of the next release cut, and we're still working on getting them some more bake time.

Are you okay with something like pointing at a specific commit rather than a release branch during the interim period?

**Comment by fsaintjacques** [comment]
I'm ok with pinning the version to a specific commit.

**Comment by fsaintjacques** [comment]
@shollyman since you seem close to the storage write team, I'll point you to a ticket I opened: https://issuetracker.google.com/issues/249245481

**Review by alvarowolfx — APPROVED** [review]
LGTM

**Pull request merged**
