### PR TITLE
fix(pubsub/pstest): start `DeliveryAttempt` at 1

### PR DESCRIPTION
**Pull request by mikeklaas**
Per [the documentation](https://github.com/googleapis/google-cloud-go/blob/74da335fea6cd70b27808507f2e58ae53f5f4910/internal/pubsub/message.go#L63) and `DeliveryAttempt` should start at 1 when a dead-letter topic is enabled, not 0 as `pstest` currently returns

### CODE REVIEW

**Comment by mikeklaas** [comment]
Note: I since realized that delivery attempt isn't being set for streamingpull deliveries at all, so I'm going to update this PR to correct that as well.

**Comment by hongalex** [comment]
Thanks for opening this PR! I'll be happy to take a look once you're ready with the streaming pull changes.

**Comment by mikeklaas** [comment]
@hongalex I think this is ready for a review!  The fix to add `DeliveryAttempt` to streaming pull is a little awkward, but I think it's safe and the best way to accomplish the goal without making deeper changes to how messages are delivered.

**Comment by mikeklaas** [comment]
Happy to rebase or update the PR if helpful for reviewing.

**Review by hongalex — APPROVED** [review]
Apologies for missing this! Logic looks good to me. Yeah, we'll need to make sure this branch is up to date before merging.

**Comment by hongalex** [comment]
Looks like the tests passed though we'll need another push when you get a chance. Same with #7650 though we should merge these one at a time. Let's start with this PR

**Comment by mikeklaas** [comment]
@hongalex I've rebased several times but the commit frequency is often enough that the PR quickly gets stale again.  I'll try to keep updating it, but if you happen to have eyes on the PR and it's out of date, the GitHub `Update with rebase` works consistently, it seems.

**Comment by hongalex** [comment]
Yeah I enabled automerge, apologies for the additional work. These PRs should be merged within the next day.

**Comment by mikeklaas** [comment]
Apologies! I manually rebased the PR which disable auto-merge.  I'll stop touching it now.

**Comment by hongalex** [comment]
> Update with rebase

Apologies again for delay here. I think there's an issue here that I don't have contribution permissions to make changes to your branch, so I can't rebase onto it. Thus the "Update with rebase" option doesn't show up for me in this PR. I'm not 100% of the mechanics but I was able to rebase onto other people's branches before. Perhaps you could add me as a collaborator for your two branches explicitly?

**Comment by mikeklaas** [comment]
> Apologies again for delay here. I think there's an issue here that I don't have contribution permissions to make changes to your branch, so I can't rebase onto it. Thus the "Update with rebase" option doesn't show up for me in this PR. I'm not 100% of the mechanics but I was able to rebase onto other people's branches before. Perhaps you could add me as a collaborator for your two branches explicitly?

@hongalex I invited you as a collaborator with write access to the forked project.  Do you think that would work?

**Comment by hongalex** [comment]
> > Apologies again for delay here. I think there's an issue here that I don't have contribution permissions to make changes to your branch, so I can't rebase onto it. Thus the "Update with rebase" option doesn't show up for me in this PR. I'm not 100% of the mechanics but I was able to rebase onto other people's branches before. Perhaps you could add me as a collaborator for your two branches explicitly?
> 
> @hongalex I invited you as a collaborator with write access to the forked project. Do you think that would work?

Great, that worked. I'll update and merge later today.

**Pull request merged**
