### PR TITLE
docs(firestore): added `!=` and `not-in` to godoc

### PR DESCRIPTION
**Pull request by 54m**
fix godoc for firestore v1.4.0 (`!=` & `not-in`)

### CODE REVIEW

**Review by codyoss — COMMENTED** [review]
LGTM, but will let @crwilcox have the final say.

**Comment by 54m** [comment]
@codyoss 
change the commit message?

**Comment by codyoss** [comment]
@54m You can if you like, or we can update it when to squash and merge. Up to you 😄  Thanks for the contribution!

**Comment by 54m** [comment]
@codyoss done.

**Review by crwilcox — DISMISSED** [review]

**Comment by 54m** [comment]
@codyoss What happened?

**Review by tritone — APPROVED** [review]

**Comment by tritone** [comment]
Looks like we didn't have an approving review. Also, merge on green sometimes doesn't work on community contributions since the CI doesn't run automatically. I will try to merge now.

**Comment by 54m** [comment]
@tritone Thank you for running the CI.

**Pull request merged**
