### PR TITLE
bigtable: Update user-agent to the latest version

### PR DESCRIPTION
**Pull request by mohanli-ml**
Currently the user agent of Bigtable in Go is standalone, as in https://github.com/googleapis/google-cloud-go/blob/master/bigtable/doc.go#L121m. Update it to the latest version https://pkg.go.dev/cloud.google.com/go/bigtable. Related issue: https://github.com/googleapis/google-cloud-go/issues/3330.

Background: DirectPath will use user agent to deny a specific library version, so we want to update the user agent with the library release date.

### CODE REVIEW

**Review by tritone — APPROVED** [review]
LGTM

@igorbernstein2 @tbpg is there any reason we can't either 1. Use https://github.com/googleapis/google-cloud-go/blob/40f29fe4298f1cb22cee0fe509ed95ac2ef7c531/internal/version/version.go#L29 for this, which is used by at least some other packages, or 2. Switch to using the release tag itself?

It's easy to forget to update this value as is (as evidenced by the fact that it hasn't been updated in 2.5 years).

**Comment by codyoss** [comment]
@tritone I will be changing this soon to be the actual tag as a part of #2749.

**Comment by codyoss** [comment]
@mohanli-ml Won't direct path be denied in older version automatically since the new option is not being sent, why is extra header validation needed? Also, like you mention in #3330 ideally this would be semver. If we switch this header to be semver you would no longer be able to parse a date for this feature.

**Comment by mohanli-ml** [comment]
@codyoss Yes, older versions before directpath release will not support directpath. However, we need this user agent for future. For example, we might have 3 versions that can support DP, and we realize one version has some problem, so we want to deny that one, but leave the other two still use DP. And for semver, both semver and date can work, as long as the user agent is compatible with the library version. Let me know if you have more questions. Thanks!

**Comment by codyoss** [comment]
@tritone Is this still waiting on anything? My comments were just that and don't want to hold anything up here.

**Comment by tritone** [comment]
I'm fine with the switch to use the semver here. @igorbernstein2 @kolea2 can you confirm that this won't cause any backend or data collection issues that you know of?

**Review by kolea2 — APPROVED** [review]

**Pull request merged**
