### PR TITLE
fix(bigtable/bttest): fix ModifyColumnFamilies to purge data

### PR DESCRIPTION
**Pull request by dragonsinth**
- Adds TestModifyColumnFamilies to test that it works

Tested vs. real bigtable.

### CODE REVIEW

**Comment by dragonsinth** [comment]
@jhump

**Comment by dragonsinth** [comment]
https://github.com/googleapis/google-cloud-go/issues/4202

**Review by crwilcox — APPROVED** [review]
@igorbernstein2 ?

**Comment by dragonsinth** [comment]
(manually resolved merge and force-pushed)

**Comment by dragonsinth** [comment]
I'm not really sure what went wrong 🤷

**Comment by crwilcox** [comment]
@dragonsinth our automation was unable to merge as other changes occurred. I will update the branch and rerun our tests ;)

**Comment by dragonsinth** [comment]
Thank you! 😄

**Pull request merged**
